name: New Issue Action

on:
  issues:
    types: [opened]

jobs:
  respond_to_new_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to new issue
        uses: peter-evans/create-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Thank you for opening this issue! This is created with action
