name: New Issue Action

on:
  issues:
    types: [opened]

jobs:
  call_yougile_api:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to new issue
        run: |
          echo "New issue opened!"
          # Add your custom logic here
